### ISSUE TITLE
Use pysam :)

### ISSUE THREAD

**Issue by yhoogstrate** [luidale/starpa#1]
That will make life much easier, for instance reading or setting the `NH:i:` tag or sorting

**Comment by luidale** [comment]
Thanks for recommendation. I discarded pysam as I want to run it under pypy and pysam is not compatible with that (rigth?).
In addition I am just parsing sam or bam files (not looking up regions). I think I tested that simple parsing is faster than doing it through pysam.
In the future I will add pybam (converted to Python3) which is speeding up parsing a bit and works under pypy.
